apiVersion: v1
kind: Service
metadata:
  name: kube-avroin-jsonout-svc
spec:
  type: LoadBalancer
  selector:
    app: kube-avroin-jsonout
  ports:
    - name: http
      port: 9090
      targetPort: 9090