apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: flink-avro-topic-sink
  namespace: confluent
spec:
  name: flinkAvroTopicSink
  replicas: 1
  partitionCount: 3
  kafkaClusterRef:
    name: kafka
    namespace: confluent
  configs:
    cleanup.policy: "delete"
